# Generated by Django 4.1.4 on 2023-01-03 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='authot',
            new_name='author',
        ),
    ]
