# Generated by Django 4.1.4 on 2023-01-04 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_rename_authot_post_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image_name',
            field=models.FileField(upload_to='posts'),
        ),
    ]
